project_id = "vplasmjfvhzcjpfpebvy"

[functions.create-wedding]
verify_jwt = false

[functions.list-weddings]
verify_jwt = false

[functions.get-wedding-details]
verify_jwt = false

[functions.submit-wish]
verify_jwt = false

[functions.delete-wedding]
verify_jwt = false

[functions.update-guest]
verify_jwt = false

[functions.get-guests]
verify_jwt = false

[functions.extend-wedding]
verify_jwt = false

[functions.fetch-wishes]
verify_jwt = false

[functions.verify-guest]
verify_jwt = false

[functions.delete-guest]
verify_jwt = false

[functions.mark-wishes-read]
verify_jwt = false

[functions.send-whatsapp]
enabled = true
verify_jwt = true
import_map = "./functions/send-whatsapp/deno.json"
entrypoint = "./functions/send-whatsapp/index.ts"

[functions.debug-db]
enabled = true
verify_jwt = true
import_map = "./functions/debug-db/deno.json"
entrypoint = "./functions/debug-db/index.ts"

