project_id = "knmqezafmenqghiheloi"

[functions.create-wedding]
verify_jwt = false

[functions.list-weddings]
verify_jwt = false

[functions.get-wedding-details]
verify_jwt = false

[functions.submit-wish]
verify_jwt = false

[functions.delete-wedding]
verify_jwt = false

[functions.update-guest]
verify_jwt = false

[functions.get-guests]
verify_jwt = false

[functions.extend-wedding]
verify_jwt = false

[functions.fetch-wishes]
verify_jwt = false

[functions.send-whatsapp]
enabled = true
verify_jwt = true
import_map = "./functions/send-whatsapp/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-whatsapp/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-whatsapp/*.html" ]
